### PR TITLE
reflect mimesis module renaming

### PR DESCRIPTION
**Pull request by nschlemm**
As stated in https://github.com/lk-geimfari/mimesis/blob/master/CHANGELOG.rst#version-300:
...
- Renamed module ``config.py`` to ``locales.py``
...

this should update PR #49

### CODE REVIEW

**Comment by sobolevn** [comment]
@nschlemm awesome! Thanks!

I will release a new version this week.

**Comment by nschlemm** [comment]
@sobolevn do you need any further help with that release?

I'm not sure what the best fix for the failing `test_data_with_override_defined_locale` in https://travis-ci.org/mimesis-lab/mimesis-factory/builds/481677397 is .. my guess is that it fails on something like any of these  `O'...`surnames: https://github.com/lk-geimfari/mimesis/blob/master/mimesis/data/en/person.json#L5510-L5515 but just making the `test_data_with_override_defined_locale` pass by adding the `'` in https://github.com/mimesis-lab/mimesis-factory/blob/dependabot/pip/mimesis-3.0.0/tests/test_locale_override.py#L51 would be a **really** nasty quick fix ...

**Comment by sobolevn** [comment]
Sorry, but I am quite busy at the moment. 

@lk-geimfari can you please help @nschlemm to make the release?

**Comment by lk-geimfari** [comment]
I'm not sure about compatibility with Mimesis 3.0.0. @nschlemm, tell me, please, do you check it out?

**Pull request merged**
